set ANSI_NULLS ON
set QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [dbo].[PRO_UPDATE_KHACHHANG]  
	
	@ID NVARCHAR(5),
	@HOTEN NVARCHAR(50),
	@SDT NVARCHAR(13),
	@DIACHI NVARCHAR(200)
AS
BEGIN
	
	
	UPDATE dbo.tbl_KhachHang
	SET sHoTen = @HOTEN, sSoDienThoai = @SDT, sDiaChi = @DIACHI
	WHERE PK_KhachHang = @ID

END

set ANSI_NULLS ON
set QUOTED_IDENTIFIER ON




