/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Login.java
 *
 * Created on Aug 15, 2011, 12:49:07 AM
 */
package admin;

import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import module.GetScreenSize;

/**
 *
 * @author liemmaster
 */
public class Login extends javax.swing.JFrame {

    /** Creates new form Login */
    public Login() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panDangNhap = new javax.swing.JPanel();
        lblMaNhanVien = new javax.swing.JLabel();
        txtMaNhanVien = new javax.swing.JTextField();
        lblMatKhau = new javax.swing.JLabel();
        txtMatKhau = new javax.swing.JPasswordField();
        chkNhoTaiKhoan = new javax.swing.JCheckBox();
        lblQuyenMatKhau = new javax.swing.JLabel();
        btnDangNhap = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        lblThongBao = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ä�Äƒng nháº­p");
        setAlwaysOnTop(true);
        setBounds(new java.awt.Rectangle(200, 200, 0, 0));
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.TOOLKIT_EXCLUDE);
        setName("fraLogin"); // NOI18N
        setResizable(false);
//        setType(java.awt.Window.Type.UTILITY);

        panDangNhap.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ThÃ´ng tin tÃ i khoáº£n", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, java.awt.Color.black));

        lblMaNhanVien.setText("MÃ£ nhÃ¢n viÃªn: ");

        txtMaNhanVien.setText("admin");

        lblMatKhau.setText("Máº­t kháº©u: ");

        txtMatKhau.setText("admin");

        chkNhoTaiKhoan.setText("Nhá»› tÃ i khoáº£n");

        lblQuyenMatKhau.setForeground(new java.awt.Color(0, 51, 255));
        lblQuyenMatKhau.setText("QuyÃªn máº­t kháº©u?");
        lblQuyenMatKhau.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnDangNhap.setText("Ä�Äƒng nháº­p");
        btnDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangNhapActionPerformed(evt);
            }
        });

        btnThoat.setText("ThoÃ¡t");

        lblThongBao.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        lblThongBao.setForeground(new java.awt.Color(255, 0, 0));
        lblThongBao.setText(" ");

        javax.swing.GroupLayout panDangNhapLayout = new javax.swing.GroupLayout(panDangNhap);
        panDangNhap.setLayout(panDangNhapLayout);
        panDangNhapLayout.setHorizontalGroup(
            panDangNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panDangNhapLayout.createSequentialGroup()
                .addGroup(panDangNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panDangNhapLayout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(btnDangNhap)
                        .addGap(18, 18, 18)
                        .addComponent(btnThoat))
                    .addGroup(panDangNhapLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panDangNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMaNhanVien)
                            .addComponent(lblMatKhau))
                        .addGap(18, 18, 18)
                        .addGroup(panDangNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblThongBao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                            .addGroup(panDangNhapLayout.createSequentialGroup()
                                .addComponent(chkNhoTaiKhoan)
                                .addGap(18, 18, 18)
                                .addComponent(lblQuyenMatKhau, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE))
                            .addGroup(panDangNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtMatKhau, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtMaNhanVien, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        panDangNhapLayout.setVerticalGroup(
            panDangNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panDangNhapLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panDangNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMaNhanVien)
                    .addComponent(txtMaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panDangNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMatKhau)
                    .addComponent(txtMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panDangNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkNhoTaiKhoan)
                    .addComponent(lblQuyenMatKhau))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panDangNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThoat)
                    .addComponent(btnDangNhap))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblThongBao))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /*
     * ***********************************************
     * CÃ¡c hÃ m phá»¥c vá»¥ cÃ¡c chá»©c nÄƒng
     */
    private Boolean isValidInput(String sMaNhanVien, String sMatKhau)
    {
        Boolean result = true;
        if(sMaNhanVien.equals(""))
        {
            lblMaNhanVien.setForeground(Color.red);
            lblThongBao.setText("MÃ£ nhÃ¢n viÃªn lÃ  báº¯t buá»™c!");
            return false;
        }
        if(sMaNhanVien.length() != 6)
        {
            lblMaNhanVien.setForeground(Color.red);
            lblThongBao.setText("MÃ£ nhÃ¢n viÃªn gá»“m 6 kÃ½ tá»±!");
            return false;
        }
        
        if(sMatKhau.equals(""))
        {
            lblMatKhau.setForeground(Color.red);
            lblThongBao.setText("Máº­t kháº©u lÃ  báº¯t buá»™c!");
            return false;
        }
        
        if(sMatKhau.length() < 4)
        {
            lblMatKhau.setForeground(Color.red);
            lblThongBao.setText("Máº­t kháº©u pháº£i lá»›n hÆ¡n 4 kÃ½ tá»±!");
            return false;
        }
        return result;
    }
    
    private void btnDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangNhapActionPerformed
        String sMaNhanVien = txtMaNhanVien.getText().trim().toUpperCase();
        String sMatKhau = txtMatKhau.getText().trim();
        
        if(! isValidInput(sMaNhanVien, sMatKhau))
        {
            return;
        }
        
        LoginCode vaLogin = new LoginCode();
        if(vaLogin.ValidLogin(sMaNhanVien, sMatKhau))
        {
            JOptionPane.showMessageDialog(this, "Ä�Äƒng nháº­p thÃ nh cÃ´ng!","Ä�Äƒng nháº­p",JOptionPane.INFORMATION_MESSAGE);
        }
        else
        {
            panDangNhap.setForeground(Color.yellow);
            lblThongBao.setText("Sai mÃ£ nhÃ¢n viÃªn hoáº·c máº­t kháº©u!");
            //JOptionPane.showMessageDialog(this, "Ä�Äƒng nháº­p khÃ´ng thÃ nh cÃ´ng!\nSai mÃ£ nhÃ¢n viÃªn hoáº·c máº­t kháº©u.","Ä�Äƒng nháº­p",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnDangNhapActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() 
            {
                Login loginApp = new Login();
                GetScreenSize size = new GetScreenSize();
                loginApp.setVisible(true);
                loginApp.setBounds(size.getWidth()/2 - loginApp.getWidth()/2, size.getHeigth()/2 - loginApp.getHeight()/2, loginApp.getWidth(), loginApp.getHeight());
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangNhap;
    private javax.swing.JButton btnThoat;
    private javax.swing.JCheckBox chkNhoTaiKhoan;
    private javax.swing.JLabel lblMaNhanVien;
    private javax.swing.JLabel lblMatKhau;
    private javax.swing.JLabel lblQuyenMatKhau;
    private javax.swing.JLabel lblThongBao;
    private javax.swing.JPanel panDangNhap;
    private javax.swing.JTextField txtMaNhanVien;
    private javax.swing.JPasswordField txtMatKhau;
    // End of variables declaration//GEN-END:variables
}
